name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  ccl_ui:
    path: ../packages/ccl_ui

  ccl_data:
    path: ../packages/ccl_data

  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.5
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_arb_translator: ^1.0.15
  dependency_validator: ^4.1.0

dependency_overrides:
  ccl_services:
    path: ../packages/ccl_services

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

scripts:
  gen_changelog: git-chglog -o CHANGELOG.md
  gen_release_note: git log --pretty="- %s (%an)" $(git describe --tags --abbrev=0$(git rev-list --tags --skip=1 --max-count=1))..HEAD > release_note.txt
  gen_locale: flutter pub run easy_localization:generate -S "assets/langs" -f keys
  gen_launcher_icons: flutter pub run flutter_launcher_icons
  gen_splash: dart run flutter_native_splash:create
  run_dependency_validator: dart run dependency_validator
  run_translator: flutter pub run flutter_arb_translator:main --from en --to si --to ta --service google -p intl -o true
  build_prod_apk: flutter build apk -t lib/main_prod.dart --flavor prod
  build_prod_bundle: flutter build appbundle -t lib/main_prod.dart --flavor prod
  build_prod_ios: flutter build ios -t lib/main_prod.dart --flavor prod
  build_uat_apk: flutter build apk -t lib/main_uat.dart --flavor uat
  build_uat_bundle: flutter build appbundle -t lib/main_uat.dart --flavor uat
  build_qa_apk: flutter build apk -t lib/main_qa.dart --flavor qa
  build_qa_bundle: flutter build appbundle -t lib/main_qa.dart --flavor qa
  build_qa_ios: flutter build ios -t lib/main_qa.dart --flavor qa
  build_dev_apk: flutter build apk -t lib/main_dev.dart --flavor dev
  build_dev_bundle: flutter build appbundle -t lib/main_dev.dart --flavor dev
